[package]
name = "dissonia-codec-flac"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
dissonia-core.workspace = true
md-5 = { version = "0.10", default-features = false }

[lints]
workspace = true