[package]
name = "dissonia-codec-opus"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
dissonia-core.workspace = true
oporus = "0.2.4"

[lints]
workspace = true
