[package]
name = "dissonia-codec-opus"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
dissonia-core = { path = "../dissonia-core" }
mousiki = { git = "https://github.com/mlm-games/mousiki-recovered" }

[lints]
workspace = true
