[package]
name = "dissonia"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["pcm", "opus", "flac", "riff", "ogg", "flac-container"]
pcm = ["dep:dissonia-codec-pcm"]
opus = ["dep:dissonia-codec-opus"]
flac = ["dep:dissonia-codec-flac"]
riff = ["dep:dissonia-format-riff"]
ogg = ["dep:dissonia-format-ogg"]
flac-container = ["dep:dissonia-format-flac"]

[dependencies]
dissonia-common.workspace = true
dissonia-core.workspace = true
dissonia-codec-pcm = { workspace = true, optional = true }
dissonia-codec-opus = { workspace = true, optional = true }
dissonia-codec-flac = { workspace = true, optional = true }
dissonia-format-riff = { workspace = true, optional = true }
dissonia-format-ogg = { workspace = true, optional = true }
dissonia-format-flac = { workspace = true, optional = true }

[lints]
workspace = true