[package]
name = "dissonia-format-riff"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
dissonia-common.workspace = true
dissonia-core.workspace = true

[lints]
workspace = true